### PR TITLE
Add camera aux

### PR DESCRIPTION
**Pull request by timsainb**

### CODE REVIEW

**Comment by timsainb** [comment]
This is a minor (but imo important) change with saves the GPIO state of the basler camera alongside the basler frame number to sync the pulse of the arduino to the cameras.

**Comment by jonahpearl** [comment]
Also I assume you've tested this on your rig?

**Comment by timsainb** [comment]
Yeah it works on my rig

**Comment by timsainb** [comment]
Haven’t tried it with an azure

**Comment by jonahpearl** [comment]
ok i'll pull it down onto my rig and double check it's ok with an azure tomorrow. seems like it will work

**Comment by jonahpearl** [comment]
the line status feature works well on my rig. rn it's saving as an integer like "2" or "6" since it's being decoded from a binary number about all 3 lines. do we want to force the user to specify which line is the aux line, and then parse that into a 0/1? Seems like it will save hair pulling down the line to parse that up front.

**Comment by timsainb** [comment]
I’m lean toward no. Different basler cameras have different numbers of
gpios

Tim Sainburg <https://timsainburg.com/>
Postdoctoral Fellow
Harvard Medical School
814.574.7780, ***@***.***

**Pull request merged**
